### ISSUE TITLE
Local install instructions are wrong

### ISSUE THREAD

**Issue by nononouser** [152334H/tortoise-tts-fast#35]
ModuleNotFoundError: No module named 'k_diffusion' error when running command for output

Have installed k_diffusion https://github.com/crowsonkb/k-diffusion/ and tested several times with its contents in a different location/in path for reference from command, yet result is the same

**Comment by nononouser** [comment]
ModuleNotFoundError: No module named 'tortoise.dpm_solver_pytorch'

new one

**Comment by nononouser** [comment]
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by nononouser** [comment]
think i just need to uninstall and reinstall everything at this point

**Comment by nononouser** [comment]
And your python command doesnt work.. really needs revising. will stay away until its fixed

**Comment by nononouser** [comment]
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-resources>=3.2.0 from https://files.pythonhosted.org/packages/38/71/c13ea695a4393639830bf96baea956538ba7a9d06fcce7cef10bfff20f72/importlib_resources-5.12.0-py3-none-any.whl (from matplotlib==3.7.0->-r requirements.txt (line 488))
    
    
    more mistakes

**Comment by nononouser** [comment]
going back to normal ttts

**Comment by absane** [comment]
Honestly, I was having a chuckle reading this as if you were talking with yourself.

That said, this project works fine, albeit some of the documentation could be improved. But, even then it isn't that difficult to get it running. If you don't place projects into virtual environments (poetry, conda, venv, etc), because you have a habit it of doing `pip install` and `sudo pip install` on your main system, you're going to have a bad time. Classic example is `librosa` and `torch` problems.

If I were you, I'd clear every Python package/library you have, nuke every installation of Python you have, and start over. Install Miniconda and Poetry. This project is easy to install if you do it within Poetry.

Outside of Poetry, I can't get this to work at all because I have several dependency conflicts that otherwise result in dependency hell. But once I run `poetry shell` it all works flawlessly.
