### ISSUE TITLE
can't get conditioning latents?

### ISSUE THREAD

**Issue by Disastorm** [152334H/tortoise-tts-fast#43]
This function works for me on the official tortoise-tts repo, but on this fast repo it fails with 
"IndexError: too many indices for tensor of dimension 1" on line 138 of tortoise/api.py

This is the function I'm referring to.
```
auto_conditioning, diffusion_conditioning, _, _ = tts.get_conditioning_latents(
                voice_samples=reference_clips,
                return_mels=True,
            )
```
It also fails if I set original_tortoise=True.
Also, if I use the tts function with reference clips, it fails with the same error.

However, if I replace the entire get_conditioning_latents function with the official tortoise-tts repo's function it works.

**Comment by 152334H** [comment]
generally this is a problem with using reference clips from somewhere that doesn't eventually go to `load_required_audio`, because the code was changed to receive a pair of reference clips at 22.05khz && 24khz respectively.

I can't guess how exactly you're deriving the reference clips from, but you should try to use `utils.audio.load_voice`(`s`) instead

**Comment by Disastorm** [comment]
Thanks, that worked. I'll close this.
