### ISSUE TITLE
requirements error - 'gdown'

### ISSUE THREAD

**Issue by nirurin** [152334H/tortoise-tts-fast#46]
Collecting gdown
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    gdown from https://files.pythonhosted.org/packages/bc/c2/bf15a3e9a5551bc13d9fce0377376e6801fa4bd9fca964dc1ee093da2559/gdown-4.6.4-py3-none-any.whl (from -r ./requirements.txt (line 1430))

**Comment by nirurin** [comment]
ModuleNotFoundError: No module named 'simple_parsing'


Also this. 

This is after installing in a totally different way to the instructions of course, as the instructions given are completely inaccurate and broken.

**Comment by xenotropic** [comment]
Also got the gdown "all requirements must have their versions pinned", just doing pip install -r requirements.txt , Ubuntu 22.04.2 LTS, pip 22.0.2, using python3.9. I'm using a `python3.9 -m pip install -r requirements.txt` command. 

When I removed gdown (it is the last line of requirements.txt), I then get 

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    numpy>=1.17 from https://files.pythonhosted.org/packages/f4/f4/45e6e3f7a23b9023554903a122c95585e9787f9403d386bafb7a95d24c9b/numpy-1.24.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=f64bb98ac59b3ea3bf74b02f13836eb2e24e48e0ab0145bbda646295769bd780 (from accelerate==0.16.0->-r requirements.txt (line 1))
```
I installed numpy=1.23.5 in a separate line, but then the next "must have their versions pinned" is typing-extensions>=3.7.4.3 . So giving up on the pip install method for now.

**Comment by xenotropic** [comment]
Okay that was false I didn't give up. The thing that tripped me up in the instructions was the "Note that if you have the original tortoise installed," and I was like "why yes I do have the original tortoise installed" so I tried to do those things first. But before installing requirements.txt you have to do the other pip3 installs listed above it.

In terms of no module named 'simple_parsing' I also got that error, but it was just that I needed to call tortoise_tts.py explicitly with python3.9 (for which I had installed all the dependencies) rather than relying on the #!/usr/bin/env python3 (which is python3.10 on my system).

**Comment by 152334H** [comment]
fires extinguished again, https://github.com/152334H/tortoise-tts-fast/commit/c34943f07196af55989b18ce860e4d5d3dbc2ee2

apologies for the slow maintenance
